[features]
seeds = false
skip-lint = false
[programs.localnet]
babel_server = "CBoo3NzDQgy9h2F7sJ4QSJKBJfWyDACFjJgRQLh7fhgg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/avishkar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
